name: bloc_getit_provider
description: "A way to use Blocs and Cubits registered in GetIt with flutter_bloc's BlocProvider"
version: 0.0.1
homepage: https://github.com/thecodebrothers/bloc_getit_provider
repository: https://github.com/thecodebrothers/bloc_getit_provider

environment:
  sdk: ^3.10.7
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^9.2.0
  flutter_bloc: ^9.1.1
  get_it: ^9.2.1
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

